name: Docs

on:
  push:
    branches:
      - docs-debug

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: VitalyArt/hltv-demo-parser
          TARGET_BRANCH: docs-debug
          BUILD_SCRIPT: npm ci && npm run docs:build
          BUILD_DIR: docs/.vuepress/dist/
