name: CI
on: [push]

jobs:
  test-php73:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - name: PHPUnit Tests
        uses: php-actions/phpunit@9
        with:
          bootstrap: vendor/autoload.php
          configuration: tests/phpunit.xml
          args: --coverage-text
          php_version: "7.3"